### ISSUE TITLE
Rael_Componentes_Personalizados

### ISSUE THREAD

**Issue by RaelRGB** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-RAEL12345#2]
[RaelComponentesPersonalizados.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-RAEL12345/files/8834140/RaelComponentesPersonalizados.pdf)

**Comment by EvelynLopezz** [comment]
Calificación 18.5

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
